### PR TITLE
Update the symfony-2.8 branch with latest changes

### PR DESCRIPTION
**Pull request by battye**
@Crizz0 - Something I've been playing with. I merged your latest version into symfony-2.8, then wiped the composer.lock changes and did a fresh composer install.

Would you be able to try testing this too? Thanks

### CODE REVIEW

**Comment by Crizz0** [comment]
I've tested this with phpBB 3.3.0 packages between "en" and "es".

And 3.2.9 packages with "en" and "tr".

In both cases, with forced errors and stuff, the result between this branch/PR and the 1.5.2-release are the same.

So looks good to me :)

**Comment by DavidIQ** [comment]
This only works on PHP 7.1 and up right?

**Comment by Crizz0** [comment]
> 
> 
> This only works on PHP 7.1 and up right?

I did run my tests of the TV with this branch locally with PHP 5.6 and PHP 7.2.26. Worked fine.

**Comment by DavidIQ** [comment]
Why are the Travis tests for 5.6 and 7.0 failing then?

**Comment by Crizz0** [comment]
Because a few dependencies require PHP 7.0/7.1 and it looks like, the package built stops immediately in the travis test. Maybe something we could improve further.

**Pull request merged**
