### PR TITLE
v1.5.0 Release

### PR DESCRIPTION
**Pull request by battye**
Steps:

- [x] ~~Test the changes in v1.5.0 against the 3.2.5 language packs~~
- [ ] Merge this PR
- [ ] Tag the newly created merge commit as release-1.5.0
- [ ] Create the v1.5.0 release on GitHub
- [ ] Update the Packagist page to show v1.5.0

Changes in this version:

* Add safe mode to parse files (using https://github.com/battye/php-array-parser) instead of including them (for use on the website in Titania)
* Update Symfony version
* Fix unit tests
* Remove phpBB 3.0 and 3.1 references

The 3.2 directory:

* I had a look and ended up not adding it to the repository, just because we don't actually require it to be in the root. If the `package-dir` is used and points to another directory outside of our structure, that will work too:

```
     php translation.php validate fr 
        --package-dir=/path/to/your/3.2 
        --phpbb-version=3.2 
        --safe-mode 
        --display-notices
```

### CODE REVIEW

**Comment by battye** [comment]
@Crizz0 How do we update packagist?
Is this something @DavidIQ can help us with?

**Comment by Crizz0** [comment]
According to Marc, only nickvergessen can help us. I wrote him.

**Comment by Crizz0** [comment]
Packagist updated

**Comment by battye** [comment]
Ah terrific, thanks @Crizz0 

Is @nickvergessen the only one with access to the phpBB Packagist account?

**Comment by Crizz0** [comment]
No, but for this repo he was the only maintainer. 

Am 17. April 2019 12:43:29 MESZ schrieb battye <notifications@github.com>:

**Comment by nickvergessen** [comment]
In fact it was bound to my personal account and no "phpbb group" account. That didn't exist back then

**Pull request merged**
